services:
  app:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
      target: local
    image: laravel/php-apache
    container_name: ${COMPOSE_PROJECT_NAME}.app
    ports:
      - ${WEB_PORT}:80
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/var/www/laravel
    networks:
      - "backend"
  db:
    container_name: "${COMPOSE_PROJECT_NAME}.db"
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - "db:/var/lib/mysql"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      interval: 3s
      retries: 10
    ports:
      - "${DB_PORT}:3306"
    networks:
      - backend
networks:
  backend:
    name: "${COMPOSE_PROJECT_NAME}_backend"
volumes:
  db:
