name: Laravel Docker test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy .env
        run: cp .env.example .env

      - name: Build docker images & run docker containers
        run: |
          echo "---Building images and starting up docker---"
          docker compose up -d
          echo "---Containers up---"

      - name: Copy .env in Laravel project
        run: |
          cd src
          cp .env.example .env
          cd ..
      
      - name: npm install in Laravel project
        run: |
          cd src
          npm install
          cd ..
      
      - name: change laravel folder permissionto user
        run: |
          docker compose exec --user user app chown -R user:user /var/www/laravel
      
      - name: composer install in Laravel project
        run: |
          docker compose exec --user user app composer install

      - name: Execute Laravel commands in the app container
        run: |
          docker compose exec --user user app php artisan key:generate
          docker compose exec --user user app php artisan migrate:fresh --seed

      - name: Perform PHPUnit test
        run: |
          docker compose exec --user user app php artisan test
